- python/tk_framework_desktopserver/message_host.py
- python/tk_framework_desktopserver/process_manager.py
- python/tk_framework_desktopserver/server_protocol.py
- python/tk_framework_desktopserver/shotgun/__init__.py
- python/tk_framework_desktopserver/shotgun/api_v1.py
- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
This is more expansive than just 40784, and covers all desktopserver changes made thus far for websockets v2.
The ShotgunAPI has been broken out into v1 and v2 variants, and a factory function is provided to choose and instantiate the correct API for a given protocol version. The v1 API is almost entirely untouched, other than having been moved into a new location.
The v2 API provides `get_actions` and `execute_action` public RPC methods. All caching-related logic is managed by `get_actions`. All command execution is handled by `execute_action`.
The cache is populated by way of a subprocess that bootstraps SGTK into the tk-shotgun engine. A list of engine commands is pulled from the engine, munged a bit, and then cached into an sqlite database along with a unique identifier built from the …
> For 40784: Adds websockets protocol v2.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/constants.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
Also fixes incorrect usage of the TK_BOOTSTRAP_CONFIG_OVERRIDE environment variable.
In the event that the caching process finds shotgun_*.yml files in the config, it will make use of those rather than bootstrapping into the conventional environments. The intent is to maintain backwards compatibility.
> For #42157: Supports legacy shotgun_*.yml environments.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
* Adds support for "Check for Core Upgrades..." menu action.
* Adds support for "Check for App Upgrades..." menu action.
* Revamps logging to bring it into line with 0.18 standards.
* Resolves bug related to how config_data is cached in memory. Previously, this cache was not stored per unique entity type, which resulted in cross pollination of engine commands into incorrect entity types.
* Resolves a bug in the cache_commands script that resulted in one cache update per engine command...which is obviously not correct.
> For #41991: Adds support for remaining "special" toolkit action manu commands.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
Config descriptors are no longer queried one at a time. They come in bulk from ToolkitManager by way of `get_pipeline_configurations()`.
> For #42066: Gets config descriptors in bulk from ToolkitManager.

- hooks/browser_integration.py
- info.yml
- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/constants.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
* Fixes a bug that caused failed command executions to not report any output back to the client.
* Implements a custom log handler in `execute_command.py` that outputs to stdout and tags all log messages in such a way that...
* ...stdout can be filtered, cleaned up, and reported back to the client when a command successfully completes.
* Takes ownership of the `browser_integration.py` hook.
* Removes HTML output from core and app upgrade commands, replacing it with simple markdown.
> For #42750, #42771, #42772: QA fixes.

- python/tk_framework_desktopserver/server_protocol.py
- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
These considerations for older cores only need to occur in the portions of the `execute_command` and `cache_actions` subprocesses being run after core swap. That means portions of the logic that occur after bootstrap has completed, including logging via the Shotgun engine, and things like the "special" core upgrade menu action.
One additional fix is that the project entity associated with a PipelineConfiguration is removed from the config's entity dict. It's not needed in the wss2 API, and if it contains a project name that's unicode, we risk UnicodeDecodeErrors when that data is passed back to the client as json.
> For #41692: Changes to support 0.16.x cores with wss2.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/constants.py
If a project contains classic-style PipelineConfiguration entities, then its get_actions and engine command execution routines call through a legacy code path. This legacy path makes use of the tank command, as the v1 wss API did.
> For #43057: Implements a legacy code path for classic sgtk projects.

- python/tk_framework_desktopserver/shotgun/api_v2.py
* Entity types that have an associated shotgun_xxx.yml file in a mutable config will be added to the entity type whitelist.
* Centralizes, and caches in memory per connection, a yml file data structure. This includes the information necessary to both compute a contents hash for a mutable config, and get the shotgun_xxx.yml file names needed for the first bullet point in this list.
* A handful of small changes that came out of code review for other PRs.
* Fixes the v2 code path's cache keys for Task entities. Previously, there was a bug that caused Task entities to receive actions for their parent entity's type (ie: Shot or Asset). Now, actions are looked up specific to the given Task entity, but the cache key is constructed to include the parent entity's type. This allows for future …
> For #43058, 43060: Entity type whitelist now contains shotgun_xxx.yml types.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
* Ensures usage of the config’s stated Python interpreter.
* Extends sys.path in the cache and command subprocesses to ensure we don’t blow away PYTHONPATH entries.
> For #43032: Fixes for PYTHONPATH and Python intepreter paths.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
Additional changes:
* YML file mtime stats during cache validation is now much deeper than before. We crawl to the bottom of the config's env area.
* A sys.path bug in the caching and execution subprocesses is now resolved. We are now guaranteed to get the correct tk-core imported when the subprocesses are spawned.
The intent of these changes are to address issues raised during client testing (the sys.path issue above), and those found during QA of tk-config-default2 (the yml file mtime depth). The changes to how deep we traverse the config looking for yml files to stat necessitates running the caching validation and potential recache asynchronously. The reason for this is that on slow network storage, the time needed to crawl the config and stat the relevant yml files can be quite slow. …
> For #45375: Implements asynchronous caching.

- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
Updating to use get_core_python_location() api method instead of assuming path hierarchy.
> update to use api method for core python location

- python/tk_framework_desktopserver/shotgun/api_v2.py
We're in the process of trying to debug an intermittent local file link open bug that we're having trouble reproducing on our end. The plan right now is to handle the error case more gracefully than before, plus log additional information about which local storages the page making the open request had access to at the time the request was made.
> SG-4611: Better error handling around local file link opening, and more debug logging.

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/cache_commands.py
- tests/api_v2/test_util_methods.py
- tests/server/test_server.py
This fixes a bug where software that is assigned to multiple projects always gets filtered out. This happened because the previous code would filter out an action as soon as the project id wouldn't match one the the projects in the list, effectively preventing any combination of project to match.
I've also update the server tests so that they can be run while the Shotgun Desktop is running, since I kept making that mistake.
> For SG-4623, software with multiple projects are not actionable

- framework.py
Fixes an import that fails under python 3. This framework is loaded but not actually used when launching a project that might be using Python 3, so we only need to fix that import error.
The rest of the code will be ported when we port the site portion of the tk-desktop engine.
> SG-14617: Partial Python 3 support for tk-desktop

- python/tk_framework_desktopserver/shotgun/scripts/get_commands.py
We were using the regular json module and getting back unicodes. Passing the base_configuration descriptor as unicode was causing issues down the line because we only check against the descriptor being a string, then convert it to a dictionary. The unicode was falling through the cracks and we ended up with unicode when we were expecting a dict.
> Switched to using sgtk.util.json.load to avoid unicode in python2

- python/tk_framework_desktopserver/shotgun/api_v2.py
In my previous commit (which is now merged) I took the single loop that iterates through pipeline configurations and caches the actions and split it into 3 loops. This was done to avoid holding a lock on the cache database the entire time.
Pass 1: Collect the info needed to do a cache lookup for all the configs. 
Pass2: Read the cache for all the keys collected in pass 1
Pass3: Either use the cached value or cache new values for each config
The issue is that when Pass 1 skipped a certain config because it doesn't support the current entity type, in the original code all the rest of the steps would be skipped as well because they were part of the same loop. In the 3 pass setup, the second and third loop were still going through all configs (even the ones that were skipped in the first …
> SG-16894 Null lookup hash in cache

- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/scripts/execute_command.py
- python/tk_framework_desktopserver/shotgun/scripts/get_commands.py
Clients are running into an issue where the PYTHONPATH contains the wrong copy of sgtk in front of the correct one. This means that the wrong hooks will be searched for/loaded when they launch Maya. 
The execute_command file was recently updated to use some core utilities and the imports for these were at the top of the file. To accommodate this, the sgtk path was being added to PYTHONPATH before calling execute_command. 
In this PR I moved sgtk related imports in execute_command to run after we have modified sys.path correctly to include sgtk. At this point there will be no requirement for sgtk to be in the path before calling execute_method so I also removed the addition of sgtk to PYTHONPATH before calling execute_command in api_v2
> SG-18619 Fix for incorrect PYTHONPATH when launching Maya

- python/tk_framework_desktopserver/certificates.py
- tests/python/base_test.py
- tests/test_certificates.py
This fixes a set of issues with the certificate registration process under Python 3. I've added a test to reproduce the problem and then fix it. Unfortunately, it can't run on CI as it requires user intervention from the OS. I'm making sure it always run locally at least so this way we get some assurance that it won't be broken.
> SG-18875: localhost integration fixes under Python 3

- tests/integration_tests/interpreters.py
Azure VMs now have 3.7.9 installed on Windows instead of 3.7.{7,8}, so we're adding it to the list of versions to try.
> Adds 3.7.9 to the list of Python versions on Azure.

- framework.py
- info.yml
- python/tk_framework_desktopserver/shotgun/api_v2.py
Switched to using support_url from tk-core instead of the hard-coded  email address
> SG-20264 Support URL Update

- python/tk_framework_desktopserver/shotgun/api_v2.py
If an instance of the tk-shotgun engine was configured with no apps, or the apps didn't show in this particular instance, then it would cause an infinite loop, because we treated an empty list as if we needed to recache the actions.
> SG-19972 Fix for where we would continue to load actions when the list was empty.

- info.yml
- python/tk_framework_desktopserver/shotgun/api_v2.py
- python/tk_framework_desktopserver/shotgun/constants.py
- python/tk_framework_desktopserver/shotgun/scripts/get_commands.py
When the pick_environment hook returns None, this along with [this PR in tk-core](https://github.com/shotgunsoftware/tk-core/pull/799) will allow us to only show a warning instead of the entire stack trace every time someone navigates to the unsupported entity page in SG. 
The reason behind all of this is related to [this other PR](https://github.com/shotgunsoftware/tk-framework-desktopserver/pull/77)
> Gracefully dealing with pick_environment returning None

- python/tk_framework_desktopserver/shotgun/api_v2.py
- tests/api_v2/test_util_methods.py
- tests/integration_tests/interpreters.py
This PR fix the AttributeError: module 'cgi' has no attribute 'escape', due to the escape method is no longer supported by the cgi module. Also included  Python 3.7.17 to the azure python versions list required by the macOS image in the Azure pipeline.
> SG-31325 Replace cgi module with the html module to support the escape method.

- python/tk_framework_desktopserver/command.py
Fix deprecation warnings on Python 3.10
> Fix Python 3.10 deprecation warning

- azure-pipelines.yml
- resources/python/requirements/3.7/requirements.txt
- resources/python/requirements/3.9/requirements.txt
Twisted v23.10.0 stops support for Python 3.7. So we're keeping v22.10.0 for that specific version. We're also keeping that version for CI otherwise it breaks while installing on a Python 3.7 runner)
Resolves https://github.com/shotgunsoftware/tk-framework-desktopserver/pull/178
Resolves https://github.com/shotgunsoftware/tk-framework-desktopserver/pull/184
Resolves https://github.com/shotgunsoftware/tk-framework-desktopserver/pull/185
> SG-33714 Upgrade Twisted to 23.10.0 for Python 3.9 only

- resources/python/requirements/3.7/requirements.txt
- resources/python/requirements/3.9/requirements.txt
Please don't confuse it with SG-33306  - #180 #189.
This [new version of cryptography](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#4107---2023-11-27) released yesterday fixes CVE-2023-49083.
> SG-33722 Upgrade cryptography to 41.0.7

- resources/python/pipelines/pipelines.yml
- resources/python/requirements/3.7/requirements.txt
- resources/python/requirements/3.9/requirements.txt
- resources/python/update_requirements.py
tk-framework-desktopserver v1.6.2 updated [Cryptography 41.0.3](https://pypi.org/project/cryptography/#files) module which uses [cp37-abi3-manylinux_2_28_x86_64](https://github.com/shotgunsoftware/tk-framework-desktopserver/blob/v1.6.2/resources/python/bin/3.9/linux/cryptography-41.0.3.dist-info/WHEEL) WHEEL for both python 3.7 and 3.9 (this requires glibc 2.28 and breaks desktop menu items on CentOS7).
This PR attempts to fix this by explicitly installing a manylinux 2.17 compatible wheel on linux platforms.
> SG-34279 use manylinux 2.17 whl

- python/tk_framework_desktopserver/server_protocol.py
Sometimes `reason.value` doesn't have `message` attribute, raising a different error. This quick PR attempts to fix this.
> Improve error handling

- .snyk
- README.md
- azure-pipelines.yml
- python/tk_framework_desktopserver/__init__.py
- resources/python/README.md
- resources/python/pipelines/pipelines.yml
- resources/python/requirements/3.11/requirements.txt
- resources/python/requirements/3.7/requirements.txt
- resources/python/update_requirements.py
- Refactor some stuff to make it easier to add new versions in the future
- Print messages in console when a version is not available. Useful for debugging.
- Downgrade `setuptools` for Python 3.7 that was causing issues.
> SG-36027 Bundle modules for Python 3.11

- .snyk
- resources/python/requirements/3.10/requirements.txt
- resources/python/requirements/3.11/requirements.txt
- resources/python/requirements/3.7/requirements.txt
- resources/python/requirements/3.9/requirements.txt
- tests/README.md
Same as last year #190.
Standardize the .snyk file to match the projects on Snyk. Update to exclude directories that belong to Python 3.7 since it's no longer supported.
> SG-36829 SG-36830 - Upgrade Twisted to 24.10.0

- python/tk_framework_desktopserver/process_manager.py
Method [setResolveSymlinks()](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QFileDialog.html#PySide2.QtWidgets.PySide2.QtWidgets.QFileDialog.setResolveSymlinks) is deprecated in PySide2/PySide6. Switched to [setOptions()](https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QFileDialog.html#PySide6.QtWidgets.QFileDialog.setOptions) which is backward compatible to PySide2 as well.
> SG-37292 Update PySide6 set option syntax

- resources/python/requirements/3.10/requirements.txt
- resources/python/requirements/3.11/requirements.txt
- resources/python/requirements/3.7/requirements.txt
- resources/python/requirements/3.9/requirements.txt
- Base branch is #291 to prevent CI issues
- Bump PyOpenSSL to 25.0.0 because of dependency conflicts caused by the new version of cryptography
> SG-38248 Update cryptography to 44.0.1
